[build]
  # Alle Befehle aus dem Projekt-Root laufen standardmäßig – wir brauchen hier keine
  # Build-Command für reines Function-Deploy
  publish = "."
  functions = "netlify/functions"

[functions."*"]
  external_node_modules = ["axios", "csv-parse"]
  included_files = ["netlify/functions/hood_sync.js"]
  node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[dev]
  framework = "#static"
  port = 8888
  targetPort = 3000

[[redirects]]
  from = "/"
  to = "/.netlify/functions/hood_sync"
  status = 200

[context.production.environment]
  FEED_URL = "https://taschenparadies.de/store-api/product-export/SWPEDTVIYVJKCZK2WFO4YJZKOQ/hood"
  HOOD_PASSWORD = "Berlin47,."
  ACCOUNT_NAME = "TaschenParadies"
  HOOD_ENDPOINT = "https://www.hood.de/api.htm"

[context.deploy-preview.environment]
  FEED_URL = "https://taschenparadies.de/store-api/product-export/SWPEDTVIYVJKCZK2WFO4YJZKOQ/hood"
  HOOD_PASSWORD = "Berlin47,."
  ACCOUNT_NAME = "TaschenParadies"
  HOOD_ENDPOINT = "https://www.hood.de/api.htm"

[context.branch-deploy.environment]
  FEED_URL = "https://taschenparadies.de/store-api/product-export/SWPEDTVIYVJKCZK2WFO4YJZKOQ/hood"
  HOOD_PASSWORD = "Berlin47,."
  ACCOUNT_NAME = "TaschenParadies"
  HOOD_ENDPOINT = "https://www.hood.de/api.htm"
