[build]
  functions = "netlify/functions"

[functions.hood_sync]
  schedule = "@hourly"

[functions."*.py"]
  runtime = "python3.13"

# ────────────────────────────────────────────────────────────
# Damit netlify dev deine Python-Functions erkennt:
[dev]
  # Pfad zu deinen Functions:
  functions = "netlify/functions"
  # Port, auf dem der Dev-Server hört:
  port = 8888
# ────────────────────────────────────────────────────────────
