[build]
  functions = "netlify/functions"

[functions.hood_sync]
  schedule = "@hourly"

[functions."*.py"]
  runtime = "python3.13"

# Dieser Block bewirkt, dass netlify dev deine Functions richtig lädt:
[dev]
  functions = "netlify/functions"
  port = 8888
